### ISSUE TITLE
[Need fix]danger zone/blasting zone

### ISSUE THREAD

**Issue by gamer4eg** [Zeffuro/ZeffUI#27]
I immediately apologize for the fact that the text was generated by a google translator.

Danger zone and blasting zone are in fact the same ability. You just use one at level 80, and the other in any dungeon below level 80.
We need a fix for checking the restoration of both spells when adding one of them.
(Or how to make sure that one is displayed at level 80, and another at level 79 and below?)
![image](https://user-images.githubusercontent.com/23147230/129211321-9f25a0cc-06df-404a-aead-a2c78b2e006c.png)

**Comment by Zeffuro** [comment]
This will be slightly difficult since this is one of the more unique cases (the whole custom cooldown thing is automated by looking up the ability on xivapi and I'm trying to not have to maintain a file/database with every ability with custom properties).

So if I add this I'm not sure when since it's one of the more difficult things to implement with this current codebase

**Comment by gamer4eg** [comment]
And just add the brain, you can do it like this (example below) - can you?
![image](https://user-images.githubusercontent.com/23147230/129343282-8536ace6-5d31-49a5-a9f5-19a1038d90f4.png)

**Comment by Zeffuro** [comment]
That's maybe possible but it would need to be customly added.
I'm trying to avoid having to maintain every ability in the game every patch.

For example for Danger Zone: https://fakegaming.eu/ffxiv/spellname/index.php?name=Danger%20Zone&type=action&lang=en (based on https://xivapi.com/Action/16144 )

However since you are able to find the full details in the JSON you could try using:

`extra: {
            shares_cooldown: 16165,
        },`
(from https://fakegaming.eu/ffxiv/spellname/index.php?name=Blasting%20Zone&type=action&lang=en )
and just setting the level to the lowest level one and that could solve your problem for you now (just not in the settings itself).

You can check this file as an example where it's used: https://github.com/Zeffuro/ZeffUI/blob/master/data/abilities.js#L560

**Comment by Zeffuro** [comment]
Ok I had to do some extra stuff but this should work (and I just pushed a small update to allow this to work).

https://user-images.githubusercontent.com/4972345/129349343-216a30b8-4a25-4825-a067-c83ea0647825.mp4



`
{
        "id": "16144",
        "name": "Danger Zone",
        "name_cn": "危险领域",
        "name_de": "Sprengzone",
        "name_en": "Danger Zone",
        "name_fr": "Zone de danger",
        "name_kr": "위험 지대",
        "enabled": true,
        "tts": true,
        "ttstype": "0",
        "job": "GNB",
        "level": 18,
        "duration": "0",
        "cooldown": "30",
        "type": "CustomCooldown",
        "icon": "https://xivapi.com/i/003000/003408.png",
        "color": "--filter-light-blue",
        "order": "0",
        "extra": {
          "charges": "0"
        }
      },
      {
        "id": "16165",
        "name": "Blasting Zone",
        "name_cn": "爆破领域",
        "name_de": "Erda-Detonation",
        "name_en": "Blasting Zone",
        "name_fr": "Zone de destruction",
        "name_kr": "발파 지대",
        "enabled": true,
        "tts": true,
        "ttstype": "0",
        "job": "GNB",
        "level": 80,
        "duration": "0",
        "cooldown": "30",
        "type": "CustomCooldown",
        "icon": "https://xivapi.com/i/003000/003429.png",
        "color": "--filter-light-blue",
        "order": "0",
        "extra": {
          "charges": "0",
          "shares_cooldown": "16144",
		  "hide": true
        }
      }
`

**Comment by gamer4eg** [comment]
its work! thx!
