### ISSUE TITLE
Feature Request: Add font size and Y axis positioning

### ISSUE THREAD

**Issue by nikpietanze** [Zeffuro/ZeffUI#28]
It would be nice to be able to adjust the font size for the various bars/elements as well as the font's vertical positioning within the bar. I have been manually adjusting these values within the dev tools, but it would be nice to be able to set these values within the settings panel.

**Comment by Zeffuro** [comment]
Will need to look at this, currently font size is tied in together with the scaling because I'm unable to use transform scale for everything.

So most likely when I add it it'll have to be with an additional checkbox so to not affect every current user.

Will try to do something about this when I have the tine

**Comment by Zeffuro** [comment]
I have just finished adding static font sizes and x / y offsets.
I quickly tested them for most modules but if you notice any bug/issue let me know!

**Comment by nikpietanze** [comment]
Looks to be working great! Thanks for the quick turn around.
