### ISSUE TITLE
[Suggestion] Implement the text formatting for HP/MP

### ISSUE THREAD

**Issue by Zeffuro** [Zeffuro/ZeffUI#35]
This seems a feature people REAAAAALLY want.
The route I probably want to go with is something like what ElvUI does with their tags but keep it simplified: https://www.tukui.org/forum/viewtopic.php?f=9&t=6

**Comment by goofy-somebody** [comment]
I loved ElvUI !   Your work comes the closest to offering something similar to that functionality, especially since I use ACT already for a few things

On topic, this would be a great way to customize even further. I'm not much of a developer, but I think of modular design when it comes to those tags.

Thanks for the work you do on ZeffUI  :)

**Comment by Zeffuro** [comment]
Implemented, you can find the current tags here: https://github.com/Zeffuro/ZeffUI/blob/master/TEXTFORMAT.md
